participants:
  - el_type: geth
    el_image: ethpandaops/geth:master
    cl_type: prysm
    cl_image: jihoonsg/prysm-beacon-chain-6s:923b87f
    vc_type: prysm
    vc_image: jihoonsg/prysm-validator-6s:923b87f
    count: 7
network_params:
  genesis_delay: 20
  electra_fork_epoch: 0
  fulu_fork_epoch: 1
  perfect_peerdas_enabled: true
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
  - spamoor
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
